# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mani < Formula
  desc "CLI tool to help you manage multiple repositories"
  homepage "https://manicli.com"
  version "0.30.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alajmo/mani/releases/download/v0.30.0/mani_0.30.0_darwin_amd64.tar.gz"
      sha256 "100ab4d23369e5c0c0d015f710fabbadee100b9edef90644ab25d6816923962a"

      def install
        bin.install "mani"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alajmo/mani/releases/download/v0.30.0/mani_0.30.0_darwin_arm64.tar.gz"
      sha256 "66f4e052775590ceeaa51c58855ce447e29135345506a7188282ef78fb05e608"

      def install
        bin.install "mani"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alajmo/mani/releases/download/v0.30.0/mani_0.30.0_linux_amd64.tar.gz"
        sha256 "6d40066718a7fe12fca077cb89022c218739a5f53b3b0a61089f3874ec6e437f"

        def install
          bin.install "mani"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alajmo/mani/releases/download/v0.30.0/mani_0.30.0_linux_arm64.tar.gz"
        sha256 "8a7eb29a3a9810e7d57a2d860041fa680469dfef4bbb478f0aac8274da975405"

        def install
          bin.install "mani"
        end
      end
    end
  end
end
