# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mani < Formula
  desc "CLI tool to help you manage multiple repositories"
  homepage "https://manicli.com"
  version "0.20.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/alajmo/mani/releases/download/v0.20.0/mani_0.20.0_darwin_arm64.tar.gz"
      sha256 "67923b69178bfc06d686ee27236d9ae158210d1931929d17542b516a273d8e65"

      def install
        bin.install "mani"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/alajmo/mani/releases/download/v0.20.0/mani_0.20.0_darwin_amd64.tar.gz"
      sha256 "91b3faa34cc184fe176292b9be9e2395db4a521f2cafda4db73d659dc3ca4714"

      def install
        bin.install "mani"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/alajmo/mani/releases/download/v0.20.0/mani_0.20.0_linux_amd64.tar.gz"
      sha256 "e057f026f6fa8282374627c4fe89b8c8a261333e86548568c5487017abbe6b54"

      def install
        bin.install "mani"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alajmo/mani/releases/download/v0.20.0/mani_0.20.0_linux_arm64.tar.gz"
      sha256 "51b516923c5f103ffe68c578c4cd7b117c2fa230c245334cef1a43c61bc1635f"

      def install
        bin.install "mani"
      end
    end
  end
end
